services:
  # Service Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - baoliemkhiet-network

  # Service Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3001"
    networks:
      - baoliemkhiet-network

networks:
  baoliemkhiet-network:
    driver: bridge
