services:
  # Service Backend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../stack.env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - baoliemkhiet-network
      - nhn

  # Service Frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    env_file:
      - ../stack.env
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL_DOCKER}
    ports:
      - "3001:3001"
    networks:
      - baoliemkhiet-network
      - nhn

networks:
  baoliemkhiet-network:
    driver: bridge
  nhn:
    external: true
